spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatapp
    username: postgres
    password: postgrespass
  web:
    resources:
      static-locations: file:frontend/chatapp/build
